# Generated by Django 4.2.3 on 2023-10-25 12:05

import concurso.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0002_rename_cargo_id_cargorequisito_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vis_concursos',
            fields=[
                ('concurso_id', models.IntegerField(primary_key=True, serialize=False)),
                ('anho_concurso', models.IntegerField()),
                ('codigo_concurso', models.CharField(max_length=255)),
                ('estado_seguimiento_concurso', models.CharField(max_length=255)),
                ('es_arancelado', models.BooleanField()),
                ('estado_concurso', models.BooleanField()),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('denominacion_conc', models.CharField(max_length=255)),
                ('es_postulacion_multiple', models.BooleanField()),
                ('path_documento', models.CharField(max_length=255)),
                ('es_privado', models.BooleanField()),
                ('estado_documento', models.CharField(max_length=255)),
                ('vigente', models.BooleanField()),
            ],
            options={
                'db_table': 'vis_concursos',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='puesto',
            name='cantidad_puestos',
            field=models.BigIntegerField(blank=True, null=True, validators=[concurso.validators.validate_positive_number]),
        ),
    ]
