# Generated by Django 4.2.3 on 2023-10-25 12:14

import concurso.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0003_vis_concursos_alter_puesto_cantidad_puestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='vigencia_hasta',
            field=models.DateField(blank=True, db_comment='Fecha de fin de puesto.', null=True, validators=[concurso.validators.validate_future_date]),
        ),
    ]
