# Generated by Django 4.2.3 on 2023-10-25 17:51

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('concurso', '0003_vis_concursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'db_table': 'auth_group',
                'db_table_comment': 'Tabla de grupos de usuarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
            ],
            options={
                'db_table': 'auth_permission',
                'db_table_comment': 'Tabla de permisos de usuarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioFP',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(db_comment='Telefono de la persona.', max_length=255)),
                ('direccion_particular', models.CharField(db_comment='Direccion particular.', max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, db_comment='Fecha de nacimiento de la persona.', null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, db_comment='Lugar de nacimiento de la persona.', max_length=255, null=True)),
                ('documento', models.CharField(db_comment='Numero de documento.', max_length=15, unique=True)),
                ('apellido', models.CharField(db_comment='Apellido de la persona.', max_length=150)),
                ('nombre', models.CharField(db_comment='Nombre de la persona.', max_length=150)),
                ('correo', models.EmailField(db_comment='email', max_length=254)),
                ('usuario_nombre', models.CharField(db_comment='Nombre de usuario.', max_length=50)),
                ('password', models.CharField(db_comment='Contrasenha del usuario.', max_length=128)),
                ('estado_usuario', models.BooleanField(db_comment='Estado de la cuenta (True, False)', default=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('documento_duplicado', models.CharField(blank=True, max_length=3, null=True)),
                ('groups', models.ManyToManyField(blank=True, db_table='usuariofp_groups', related_name='usuariofp_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, db_table='usuariofp_user_permissions', related_name='usuariofp_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuariofp',
                'db_table_comment': 'Tabla de usuarios FPUNA',
            },
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='usuario',
            field=models.ForeignKey(blank=True, db_comment='Identificador de usuario.', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='concurso.usuariofp'),
        ),
        migrations.AlterField(
            model_name='usuariodocumento',
            name='usuario',
            field=models.ForeignKey(blank=True, db_comment='Identificador de usuario.', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='concurso.usuariofp'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
