# Generated by Django 4.2.3 on 2023-10-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0004_group_permission_usuariofp_alter_postulacion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariofp',
            name='documento',
            field=models.CharField(db_comment='Numero de documento.', max_length=20, unique=True),
        ),
    ]
