# Generated by Django 4.2.3 on 2023-10-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0005_alter_usuariofp_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofp',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
    ]
