# Generated by Django 4.2.3 on 2023-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0005_vistaconcurso_vistadetalleconcurso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaAreaPostula',
            fields=[
                ('puesto_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dependencia_id', models.IntegerField()),
                ('descripcion_dependencia', models.CharField(max_length=255)),
                ('area_id', models.IntegerField()),
                ('descripcion_area', models.CharField(max_length=255)),
                ('sub_area_id', models.IntegerField()),
                ('descripcion_sub_area', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vista_area_postula',
                'managed': False,
            },
        ),
    ]
