# Generated by Django 4.2.3 on 2023-10-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0007_alter_usuariofp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofp',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuariofp',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
