# Generated by Django 4.2.3 on 2023-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('concurso', '0008_usuariofp_is_staff_alter_usuariofp_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariofp',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='usuariofp_groups', related_name='usuarios', to='auth.group'),
        ),
    ]
