# Generated by Django 4.2.3 on 2023-10-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0010_alter_usuariofp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofp',
            name='idsistema',
            field=models.IntegerField(blank=True, db_comment='Identificador del sistema que se autentica', default=1, null=True),
        ),
    ]
