# Generated by Django 4.2.3 on 2023-10-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0012_usuariofp_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariofp',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuariofp',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='usuariofp',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
