# Generated by Django 4.2.3 on 2023-10-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0013_remove_usuariofp_is_active_remove_usuariofp_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariofp',
            old_name='usuario_id',
            new_name='id',
        ),
    ]
