# Generated by Django 4.2.3 on 2023-10-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0014_rename_usuario_id_usuariofp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
