# Generated by Django 4.2.3 on 2023-10-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0006_vistaareapostula'),
        ('concurso', '0015_usuariofp_is_active'),
    ]

    operations = [
    ]
