# Generated by Django 4.2.3 on 2023-10-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concurso', '0016_merge_0006_vistaareapostula_0015_usuariofp_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofp',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
