from django.contrib import admin
from .models import Direccion, Dependencia, Area, SubArea, Cargo, TipoCargo, TipoDocumento, Documento, CargoDocumento, Requisito, CargoRequisito, Carrera 
from .models import Enfasis, Asignatura, Catedra, ModalidadConcurso, TipoConcurso, Concurso, ConcursoDocumento, ConcursoRequisito, Dias, Postulacion
from .models import DocumentoPostulacion, ModalidadPuesto, Sede, Turno, TipoPuesto, Puesto, Horario, PuestoDocumento, PuestoRequisito, UsuarioFP, UsuarioDocumento
from .models import UsuarioFP

admin.site.register(Direccion)
admin.site.register(Dependencia)
admin.site.register(Area)
admin.site.register(SubArea)
admin.site.register(TipoCargo)
admin.site.register(Cargo)
admin.site.register(TipoDocumento)
admin.site.register(Documento)
admin.site.register(CargoDocumento)
admin.site.register(Requisito)
admin.site.register(CargoRequisito)
admin.site.register(Carrera)
admin.site.register(Enfasis)
admin.site.register(Asignatura)
admin.site.register(Catedra)
admin.site.register(ModalidadConcurso)
admin.site.register(TipoConcurso)
admin.site.register(Concurso)
admin.site.register(ConcursoDocumento)
admin.site.register(ConcursoRequisito)
admin.site.register(Dias)
admin.site.register(Postulacion)
admin.site.register(DocumentoPostulacion)
admin.site.register(ModalidadPuesto)
admin.site.register(Sede)
admin.site.register(Turno)
admin.site.register(TipoPuesto)
admin.site.register(Puesto)
admin.site.register(Horario)
admin.site.register(PuestoDocumento)
admin.site.register(PuestoRequisito)
admin.site.register(UsuarioFP)
admin.site.register(UsuarioDocumento)
